### ISSUE TITLE
[Suggestion] Add a new #Status channel to the chat window

### ISSUE THREAD

**Issue by JohannesMP** [godarklight/DarkMultiPlayer#116]
- Status changes such as 'user joined channel' or 'user shared screenshot' should appear in the `#Status` channel
- status notifications should appear as orange, and have lower priority than those in #Global
- See #115 for more details on color/priority

**Comment by godarklight** [comment]
I'll keep these in global, but they will no longer highlight the channel via 8018f4de9be07bc092ad33f75fef2c22e9dc10d2

**Comment by oldmud0** [comment]
@RockyTV No pointers :wink:
