### ISSUE TITLE
Lost career progress

### ISSUE THREAD

**Issue by local306** [godarklight/DarkMultiPlayer#197]
I've been playing on a server I have running on one of my computers for a few days now. I got a friend to join in recently, and the last time I tried to connect to play with him I lost all of my previous progress. Any idea how I could recover this or fix this from happening in the future?

**Comment by RockyTV** [comment]
This could've been the bug where your progress was not saved when you left the server. The bug should be fixed as of 6192598.
If it wasn't fixed, re-open this issue.

Closed #197.
