### ISSUE TITLE
Need to add "autosync" to server

### ISSUE THREAD

**Issue by Zero---Cool** [godarklight/DarkMultiPlayer#205]
I have an open issue #204 , and I figured out somewhat of a fix. Users will all need to sync to stop this freeze from occuring, is there a way to add an "AUTOSYNC" to the server code to force players all to sync their time? it could be on a timer set by the serversettings.txt and would prevent lag, and all the load issues plaguing us. Thanks!

**Comment by godarklight** [comment]
MCW* :)
