### ISSUE TITLE
"Gameplay Tweaks" does not save 

### ISSUE THREAD

**Issue by Zero---Cool** [godarklight/DarkMultiPlayer#250]
I believe since the DMP 1.5.6 the gameplay tweaks have been reverting to defualt, and preferences are not saved. Everytime the game is launched back into DMP, the gameplay tweaks go back to default. In particular: "REVERT TO LAUNCH, REVERT TO VAB" etc... wondering if there was a fix for this? Thanks!

**Comment by RockyTV** [comment]
Closed, implemented via 9e5e41c.
