### ISSUE TITLE
Revert support

### ISSUE THREAD

**Issue by godarklight** [godarklight/DarkMultiPlayer#255]
This would be nice to have. It's entirely possible to do in SUBSPACE mode - We'll drop our crappy save/load active vessel approach, but it's going to cost us memory as we have to save every position / proto update.

I'd prefer to keep this a client side option, disabled by default, or perhaps enabled with 50mb of DMP revert support.

We'll need to find out where the quicksave / revert UT is kept as well, as updates before this time can be garbage collected.

**Comment by oldmud0** [comment]
You never closed the issue :laughing:
