### ISSUE TITLE
FPS problem

### ISSUE THREAD

**Issue by exwizzard** [godarklight/DarkMultiPlayer#269]
Hello,

My FPS drops to 0 when me and my friend try to launch a space plane at the same time.

I am running windows 8.1 and the game is installed on the ssd.

**Comment by dataneger** [comment]
I think because you are launching at the same time you end up so close to each other that it consumes alot of cpu to render both players. I have alot of problems when 2 players come close to each other in my multiplayer tests.

**Comment by oldmud0** [comment]
Doesn't the "revert" feature record vessel movements to play back on time travel?

**Comment by godarklight** [comment]
Closing this and keeping #298 open
