### ISSUE TITLE
Kerbals lose career progression when disconnecting from the server

### ISSUE THREAD

**Issue by Vazrik47** [godarklight/DarkMultiPlayer#280]
Kerbals (scientist, engineer, and pilot) do not save flights/experience/progression when disconnecting from the server. 

There is also currently 5 Kerbals allowed to be "hired" on the current upgrade i have for the Astronaut Complex. When disconnecting to the server, on reconnect there are 30 Available kerbals and previously hired kerbals are no longer in my available list. New list upon connecting has to be "fired" and rehired each time on connect.

https://www.youtube.com/watch?v=V_EDaEOqdec&feature=youtu.be

Client Log file
http://pastebin.com/mwswmKSS

Server Log File
https://drive.google.com/file/d/0B0behAKpYrPYSTVxUF9ZUmZ0emc/view

**Comment by andremiller** [comment]
For me, in career mode, I'm also getting a lot of strange things happening with Kerbals. I don't know if it's related to your issue or new.

When I first started Career mode I had 20 Active kerbals, all 'Available'. Then I did a few contracts, but the last one after I splashed down I could not recover my craft, button did nothing, in fact no buttons did anything so I had to disconnect and restart.

When I restarted 17 out of those 20 Active kerbals were now listed as Lost / Missing.

**Comment by LMBlackWolf** [comment]
It seems like the server didn't save the progress correct

client (persistent.sfs) (after one flight)

name = Barrod Kerman
type = Crew
brave = 0.1777042
dumb = 0.7040561
badS = False
state = Available
ToD = 0
idx = 0
CAREER_LOG
{
	flight = 1
	0 = Flight,Kerbin
	0 = Land,Kerbin
	0 = Recover
}
FLIGHT_LOG
{
	flight = 1
}


server (Barrod Kerman.txt)

name = Barrod Kerman
type = Crew
brave = 0.1777042
dumb = 0.7040561
badS = False
state = Assigned
ToD = 0
idx = 0
CAREER_LOG
{
	flight = 0
}
FLIGHT_LOG
{
	flight = 0
	0 = Flight,Kerbin
}

**Comment by oldmud0** [comment]
What are the timestamps on each?

Also, please use <nocode>```</nocode> to wrap code. Thanks.

**Comment by godarklight** [comment]
We've got to change the way we check for protokerbal differences - Currently we only send them off if the kerbal assign status changes - now that they have attached modules we might have to do it the scenario module way instead. This also gives us 100% future compatibility to changes, and mods that use per kerbal data

**Comment by RockyTV** [comment]
Should be fixed as of 6192598.
If the issue persists, feel free to re-open this issue.

Closed #280.
