### ISSUE TITLE
Load Button Doesn't Work

### ISSUE THREAD

**Issue by Blaze1068** [godarklight/DarkMultiPlayer#285]
My load button does not work for SPH and I deleted all my saves and it still doesn't work but it works in VAB.

**Comment by godarklight** [comment]
That is awfully strange... Can you upload KSP/KSP.log to a site like pastebin (or perhaps if it's too big, email it to me? / dropbox?)

I suspect there's a dodgy vessel in the saves/DarkMultiPlayer/Ships/SPH folder, but if that's the case I question how a broken vessel got in there in the first place...

If the SPH thing does fix it, can you send them too me aswell, this is something we might need to defend against.

**Comment by Ricktza** [comment]
A friend of mine has this game issue, turned out he didn't have the ksp/ship folder missing.
don't mistaken this for ksp/saves/<savename>/ships

**Comment by godarklight** [comment]
Stock bug: https://www.youtube.com/watch?v=WkHMNUNGSic
