### ISSUE TITLE
When the sunset spell error

### ISSUE THREAD

**Issue by Pelman1488** [godarklight/DarkMultiPlayer#288]
When my friend logs on to the server Hamachi written (coneckting errore.The attempt to connect was bezuprechnoi because of another compuuter for there is no answer,or it was already broken osstanovlenie connections)

**Comment by RockyTV** [comment]
This is not a DMP issue, it is your issue.

Closed.

**Comment by godarklight** [comment]
I can only suggest double checking the hamachi addresses. Hamachi should just work...

The better alternative is port forwarding though :)
