### ISSUE TITLE
Hide joins and share screenshot messages

### ISSUE THREAD

**Issue by oldmud0** [godarklight/DarkMultiPlayer#290]
It's so annoying when the little chat button lights up whenever someone joins, leaves, or takes a screenshot, especially when I have to click on the chat menu and the screenshot menu to dismiss the message. There should be a button to stop receiving these kinds of messages.

**Comment by godarklight** [comment]
Yes it is. We'll nab this one for 0.2.1.0 :)

**Comment by godarklight** [comment]
Fixed via 8018f4de9be07bc092ad33f75fef2c22e9dc10d2
