### ISSUE TITLE
Chat activity unfocuses chat text box

### ISSUE THREAD

**Issue by oldmud0** [godarklight/DarkMultiPlayer#291]
Every time something new pops up on the chat menu, the text box gets unfocused. This is extremely annoying because SPACE then automatically stages the vessel instead of typing a space.

**Comment by godarklight** [comment]
This one too - Although I *think* what's happening here is as another element is inserted unity has an off-by-one...

This one should be pretty easy to fix for 0.2.1.0 as well.

**Comment by godarklight** [comment]
Fixed via 8018f4de9be07bc092ad33f75fef2c22e9dc10d2
