### ISSUE TITLE
We don't see each other!

### ISSUE THREAD

**Issue by Pelman1488** [godarklight/DarkMultiPlayer#292]
1 time we went we saw each other on the orbital map!But then I perezosa on the server we had not seen each other,I even tried to restart the server,reinstall the server, not what helps what to do?

**Comment by godarklight** [comment]
I'll need a log file to help you.

Upload KSP_folder/KSP.log to a site like www.pastebin.com and link it here :)

**Comment by godarklight** [comment]
Caused by throwing in ProcessNewVesselUpdates
