### ISSUE TITLE
connection error

### ISSUE THREAD

**Issue by REVIEWGAMINGMAN** [godarklight/DarkMultiPlayer#295]
![2015-01-29_13-09-58](https://cloud.githubusercontent.com/assets/4707623/5964243/348586b0-a7b8-11e4-804a-954608c91f75.png)

**Comment by oldmud0** [comment]
okay.. Plugins? Logs?

**Comment by godarklight** [comment]
If you're really connecting to localhost (127.0.0.1), you need to be running the server before the connect button will work :P

**Comment by REVIEWGAMINGMAN** [comment]
it's a host server not  localhost and in the server runs fine

**Comment by REVIEWGAMINGMAN** [comment]
Hi godarklight/DarkMult,

I'd like to add you to my professional network on LinkedIn.

- ryan

Confirm that you know ryan: https://www.linkedin.com/e/v2?e=0-iic356np-49&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=Qdq8n4L_&invitationId=6083703223485546496








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-iic356np-49&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQHIaKdhBLU74gAAAVG2n_BM8OlRuQOMJhIp-aXC4t03xYqR9JV9B-cThM60FAVBu_fccy0pbcXCom_HWblDe7-2lowl8L4IAWCzhPqCVciUDJgfD7XS5QJ_0raCncZWmMXmM5ZHBoroO9ZYH1jnz4OLfLEcQgdmEn70NEk4qmkE2bhfOfiM7QazIBaQRRxz8NFu&eid=0-iic356np-49


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-iic356np-49&a=customerServiceUrl&ek=invite_guest

&copy; 2015 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by REVIEWGAMINGMAN** [comment]
ryan lundy would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=dweepn-ij08qreq-po&a=preRegInvite&ek=first_guest_reminder_01&li=14&m=hero&ts=accept_text&sharedKey=Qdq8n4L_&invitationID=6083703223485546496

View ryan lundy&#39;s profile: https://www.linkedin.com/e/v2?e=dweepn-ij08qreq-po&a=preRegInvite&ek=first_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=Qdq8n4L_&invitationID=6083703223485546496





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=dweepn-ij08qreq-po&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=dweepn-ij08qreq-po&loid=AQHZwMCdgz0G6AAAAVIOr3hmpuQh6Rd9NVSabfm0n-Z-2A0QJ84LHb3pDixv4_LA5XKzPrqgpXIBZNzn9B6Pab6YrVyhfA2RqOoVcTpnswitDeWETpjVlh-GV9BhDbYaU8ma2BQjR2CLxa_-djC1NOXKFzUVj7K0ealpCEeUMuQGbZpA4GqgpGBIg_LxVSG5yTxK

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=dweepn-ij08qreq-po&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by RockyTV** [comment]
Locked due to spam.
