### ISSUE TITLE
Massive lagg spike

### ISSUE THREAD

**Issue by toguno** [godarklight/DarkMultiPlayer#298]
Whenever i first join any server, I get an extreme amount of lagg and drop to 4 fps. When i enter a hanger, fps goes back up to normal.

**Comment by oldmud0** [comment]
Debris, debris everywhere! That's why.

**Comment by RockyTV** [comment]
I don't think this is an actual issue with the mod itself. Might be because the server has a lot of debris/vessels, and it lags out players.

**Comment by godarklight** [comment]
@RockyTV I think it's just a fact of life with how expensive confignodes are, or the actual vessel load ittself. We should probably do a little System.Diagnostics.Stopwatch profiling to find hotspots.
