### ISSUE TITLE
Performance issue and throttle reset

### ISSUE THREAD

**Issue by x0m0n** [godarklight/DarkMultiPlayer#299]
The throttle problem couples with performance issue. Neither was a problem initially. I have a set of 6 satellites around Kerbin for remotetech, the problems was observed when I was flying to deliver those satellites in orbit. I'm the only person on the server, vessel is 493 parts, server is only running DMP, core i5 2.4Ghz, 4gb of ram, my desktop has core i7 3.6ghz, 16gb ram, gtx 470.
- Performance: The game runs slower in general, aside from VAB and SPH view, everything else are considerably slower than sandbox, same mods. Same vessel flying in sandbox is smoother, versus flying in DMP session, even changing camera view stutter. Everything else stutter, the animation of adding a maneuver node, animation of each leg of said node, orbit projection. Time often jumps to the future, ETA to Apoapsis or node. When I EVA, I see the vessel in respective to the kerbal 'jumps' from 1 place to another. Distance 500m jumps to 489m the next second, as if the whole thing is skipping through time. Once EVA I can hardly get back in, when it jumps the kerbal may clips the vessel and gets thrown out again, the performance makes it very hard to reproach again and aim for the door/ladder.
- Throttle reset: This happens same time the skipping happens. Everytime I see time/position skips, the throttle resets, but only after 70km in Kerbin (haven't tried other bodies but I suppose the key is 0 atm). In atmosphere it runs ok. Out of atmosphere it starts resetting throttle. This is the log with the few last lines being times the throttle resets
http://pastebin.com/qf32Va2s

**Comment by godarklight** [comment]
These are tracked in #269 and #258

**Comment by x0m0n** [comment]
both #269 and its referenced ticket #298 are closed, #258 is also closed. Are the fix for framerate and throttle in the pipeline already and I'm being pesky?
