### ISSUE TITLE
Outpost Disappearance and Vessel Swap

### ISSUE THREAD

**Issue by Kittenzomg** [godarklight/DarkMultiPlayer#300]
My friend started up a DMP server this past weekend and so far it's just been me and him playing on it. We've encountered 2 major issues that I haven't seen in other issue posts. We are experiencing the KIA/MIA Kerbal bug, but that's not a huge concern to me at the moment. The 2 issues are as follows.

Issue 1: 
My friend established a small Mun outpost that had 1 Kerbal still in the attached pod due to not having enough fuel to get back to Kerbin. I was doing my contract to explore the Mun and thought it would be fun to plant my flag next to his outpost because we are a bit competitive. I touched down my lander next to his outpost, planted my flag, and returned ship to Kerbin. Upon returning to Kerbin my friend stated that his outpost had disappeared. We both reconnected to the server and it had, in fact, vanished. I'm not sure if there's a way to recover vessels when this happens. I don't know if it will even happen again or this was an isolated incident.

Issue 2:

Two of my friends ships swapped places randomly when he reconnected to the server. He had a manned vessel orbiting Kerbin and one orbiting Kerbol. They swapped places leaving Jebediah lost in space orbiting Kerbol with no means to return home. Again I'm not sure if this was an isolated event or not. Hopefully!

**Comment by RockyTV** [comment]
Someth
