### ISSUE TITLE
Disconnecting right after earning science does not save your recently acquired science

### ISSUE THREAD

**Issue by RockyTV** [godarklight/DarkMultiPlayer#304]
This should be easy to fix. Check if the user earned some science, if he did, send an update message to the server.

**Comment by madolinn** [comment]
Testing this, seems to be completely random how often progress is saved. Completed 4 research gains on one flight. Reconnected. Lost all progress.

Repeated, same gains, unlocked tech, reconnected. Lost all progress.

Repeated, launched another vessel, recovered. reconnect, lost all progress.

Repeated. Waited a little while, reconnected, saved.

**Comment by sentrythethird** [comment]
Would this fix it? I have no idea how to build this, sorry.
![dmp-issue 304 321](https://cloud.githubusercontent.com/assets/761009/7580859/b0682b64-f841-11e4-9431-1bddc0d59960.jpg)

**Comment by oldmud0** [comment]
@sentrythethird All you need to do is commit those changes into a new branch and make a pull request.

**Comment by RockyTV** [comment]
A fix for this would be catching the onexit method, make it wait, send the
progress scenario node and then quit.

I have something working localy. I'll see if it works and solves this
issue.

This is also related to some crashes after force-closing KSP.

**Comment by RockyTV** [comment]
By the way, the default scenario send time is 30 seconds.

**Comment by sentrythethird** [comment]
@RockyTV I saw the default send time also but I think it should stay 30 because otherwise 
string scenarioHash = Common.CalculateSHA256Hash(scenarioBytes);
gets run more often. I figured it might cause more lag or work on cpu (though I have no idea how taxing it actually is).

**Comment by RockyTV** [comment]
Should be fixed as of 6192598.
If the issue persists, feel free to re-open this issue.

Closed #304.
