### ISSUE TITLE
Client disconnected when warping on fresh server

### ISSUE THREAD

**Issue by SamSchlegel** [godarklight/DarkMultiPlayer#305]
Client log (line 2692): http://pastebin.com/d7TSUxhV
Server log (line 96): http://pastebin.com/TXXrNPeP

**Comment by godarklight** [comment]
Fixed via f62416486c9403fcada2053c43c4f43264bccd16

**Comment by oldmud0** [comment]
Did you manually put this under SamSchlegel's name or did you actually have to pull it in?
