### ISSUE TITLE
Can't join local server

### ISSUE THREAD

**Issue by Pocketkid2** [godarklight/DarkMultiPlayer#308]
I get this error in my log file when I try to join
http://pastebin.com/6LrhpxZe

**Comment by godarklight** [comment]
Sorry for the late reply - Usually the client log is more helpful here. It's located in your KSP folder, KSP.log

**Comment by Pocketkid2** [comment]
I think I was finally able to fix it, if I can find the log i'll give it

**Comment by Acememo** [comment]
This is the same as issue #301
