### ISSUE TITLE
Cant enter space center buildings after disconnect

### ISSUE THREAD

**Issue by drewcassidy** [godarklight/DarkMultiPlayer#309]
Ofter disconnecting, even voluntarily, then reconnecting, the space center buildings can't be entered. clicking one just causes the toolbar to disappear. Restarting the game fixes this

**Comment by oldmud0** [comment]
Log?

**Comment by godarklight** [comment]
As @oldmud0 said, we'll need a log file to tackle this one. It's located at KSP/KSP.log, paste it into a site like pastebin.org and I'll comb over it :)
