### ISSUE TITLE
Cannot select objects in tracking center

### ISSUE THREAD

**Issue by drewcassidy** [godarklight/DarkMultiPlayer#310]
Objects cannot be selected in the tracking center, so flights can't be continued later

**Comment by RockyTV** [comment]
What version are you running? If I remember, those issues were fixed.

**Comment by godarklight** [comment]
We'll need a log file (KSP/KSP.log) to tackle this :)

**Comment by drewcassidy** [comment]
This was fixed when i updated, i think it was related to the vessel cache issue
