### ISSUE TITLE
Not see each other

### ISSUE THREAD

**Issue by Pelman1488** [godarklight/DarkMultiPlayer#311]
Good afternoon(evening).The problem is that when I went to orbit the earth and my friend also went into orbit around the earth! And I don't see him and he did not see. What's the problem?

**Comment by RockyTV** [comment]
Are you both synched?
What version are you using?

**Comment by Pelman1488** [comment]
How to synchronize?
Version of ksp 0.90
Version DarkMultiPlayer 0.2.1.1

**Comment by RockyTV** [comment]
Is there a sync button right next to your name (in your friend's computer/ksp) or a sync button right next to your friend's name on your KSP? If yes, click it, then you should be able to see him.

**Comment by Pelman1488** [comment]
If this button then Yes we can sync up!
We can still be the problem?

**Comment by godarklight** [comment]
It's best to upload KSP/KSP.log to a site like pastebin and let us check over it here - There's still a possibility mods are messing up a vessel sync.

If it's not obvious we'll probably have to send builds/logs back and forth, the best way to get in touch with me is my IRC channel. There's a chat thing on both www.d-mp.org and my build server godarklight.info.tm
