### ISSUE TITLE
Client (and possibly server) initial timeout and heartbeat values hardcoded

### ISSUE THREAD

**Issue by Defavlt** [godarklight/DarkMultiPlayer#319]
The heartbeat and timeout values for the client is hardcoded, as seen here:

https://github.com/godarklight/DarkMultiPlayer/blob/master/Common/Common.cs#L13
```C#
    public class Common
    {
        //Timeouts in milliseconds
        public const long HEART_BEAT_INTERVAL = 5000;
        public const long INITIAL_CONNECTION_TIMEOUT = 5000;
        public const long CONNECTION_TIMEOUT = 20000;
```

I'm not familiar with DMP's codebase, so I'm not really sure whether there's a system for loading values from a file or not but if there is, could someone point me in the right direction so I can make a patch?

**Comment by RockyTV** [comment]
What's the issue with hardcoding values that do not need to be changed?

**Comment by godarklight** [comment]
I'll open them up, it's easy enough :P

**Comment by Defavlt** [comment]
> @RockyTV 
> What's the issue with hardcoding values that do not need to be changed?

I'm on a horrible 1MB 3G line. I drop out constantly with these values and it'd be nice to play some.

**Comment by Defavlt** [comment]
> @godarklight 
> EDIT: You can just change those right now and it will work after compiling ;)

Already done, but I'd much rather stick to the "official" build rather than having to add yet another repository to my daily routine.
