### ISSUE TITLE
Kerbal's experience reset on re-logging into the server  

### ISSUE THREAD

**Issue by Royalnaga** [godarklight/DarkMultiPlayer#321]
Kerbal's experience resets on re-logging into the server.

DMP: V 0.2.2.0

**Comment by caipi-** [comment]
I think I noticed something similar, but not consistently.
Before leaving the server, try to warp ahead for a few seconds and then go back to normal speed again. I think it helps when you just create a new subspace after landing. It does fix a few other issues as well (e.g.: return from a flight, invest your research point in a technode, leave, come back, notice that the tech node is unresearched again).

**Comment by Royalnaga** [comment]
Ahh sadly it didn't help in my case

**Comment by oldmud0** [comment]
Similar to #304. For some reason, certain career data is not sent consistently to the server and thus the server seldom receives it.

**Comment by RockyTV** [comment]
Sorry for all the references. Git Bash is a bit tricky to use.
The issue should be fixed in the latest unstable/dev version. Try it out, and tell me if it worked.

Closed #321. If the issue persists, feel free to re-open the issue.

**Comment by Royalnaga** [comment]
Im still experiencing the issue sadly

**Comment by RockyTV** [comment]
Are you using the latest dev version?

**Comment by Royalnaga** [comment]
Yes

-------- Original message --------
