### ISSUE TITLE
Impossible Serveur

### ISSUE THREAD

**Issue by DalixP** [godarklight/DarkMultiPlayer#325]
Bonjours

quand je met l'IP dans le fichier sitting puis je lance DMP Serveur. DMP crash automatiquement puis en essayant de le rallumer plusieurs fois toujours crash. 

Je suis en Window Beta Preview 10 si sa aide

Merci Cordialement

**Comment by RockyTV** [comment]
It would help if you wrote in english.

Maybe it is an issue with Windows 10.

**Comment by DalixP** [comment]
Je pense aussi et oui il faudrait que j'écrive en angalis

**Comment by DalixP** [comment]
hellos

When I meet the IP in sitting Initiation can I run DMP Server. Then automatically DMP accident trying to relight the liver several always accident.

I'm Preview window Beta 10 If his help

Sincerely thank you

**Comment by RockyTV** [comment]
Google Translate couldn't help either. Anyways, upload your logfile located at `KSP durectory/KSP_data/output_log.txt` to Pastebin.com and post the link here.

**Comment by DalixP** [comment]
file:///D:/Games/Kerbal%20Space%20Program/KSP_Data/output_log.txt

**Comment by RockyTV** [comment]
Copy the contents of it and upload to Pastebin.com. Then paste the generated link in here.

**Comment by DalixP** [comment]
they tell me that I exceeded the line they wonder a pro version

**Comment by RockyTV** [comment]
Upload the file to a file host then.

**Comment by DalixP** [comment]
http://pastebin.com/E4eYEfum and http://pastebin.com/E4eYEfum

**Comment by Neouni** [comment]
[66,31537] DarkMultiPlayer: Connexion à 25.120.162.183 le port 6702 ...
[67,54771] DarkMultiPlayer: Déconnecté, motif: Annulé la connexion au serveur

Basically tried to connect to server
Server cancelled connection, guess in this situation it means refused.

So ports are closed ?

**Comment by DalixP** [comment]
I think

**Comment by RockyTV** [comment]
Just wondering, why are these two lines that @Neouni listed in french? IIRC they should be in english.

**Comment by DalixP** [comment]
I think it's because of my mod that puts the game in French

**Comment by RockyTV** [comment]
Do you have the line which says that DarkMultiPlayer was initialized? If yes, post it here.

**Comment by DalixP** [comment]
Or I can find it?

**Comment by RockyTV** [comment]
Upload your log file to a file hosting service like MediaFire, MEGA,
Dropbox.

**Comment by DalixP** [comment]
I found the problem is my windows version 10 thank you for help ! :)
