### ISSUE TITLE
Kerbal's experience resets on re-logging into the server.

### ISSUE THREAD

**Issue by Royalnaga** [godarklight/DarkMultiPlayer#330]
Kerbal's experience resets on re-logging into the server.and i did use the disconnect button of DMP

Still experiencing the issue sadly even with the dev version

**Comment by RockyTV** [comment]
I think I know why it isn't saving: when you press disconnect, scenario modules are sent but not with high priority.

A fix is coming today.

**Comment by Wckdneer** [comment]
definitely still a problem. Science values etc get saved, kerbals and their XP/levels do not.

**Comment by RockyTV** [comment]
@godarklight @dsonbill suggestion: new class called KerbalWorker. You know what it must do :)

**Comment by godarklight** [comment]
Should be fixed via  31573de1a58c3dcaf875f146cbb298a2bc91f16b - but paradoxes may still mess this up.
