### ISSUE TITLE
Create a separate modcontrol file for stock parts, which can be re-written (if needed) every time when the server starts

### ISSUE THREAD

**Issue by RockyTV** [godarklight/DarkMultiPlayer#336]
This is happening to DMP when a new KSP version is released, and it includes new parts:

- We update the partslist
- Server operators update their servers, and their modcontrol file does not include the new parts from the update
- New update parts are banned from the server

We could do what @oldmud0 suggested:
> Why can't we have a "vanilla parts" file that is automatically generated ("do not edit this file") and another for modded parts (not automatically generated) and then just merge the two when we have to load/parse the mod data file?

Anyways, I'm giving it a go.

**Comment by godarklight** [comment]
Implemented via 3655d4b852f5023f7e4ab4d00ebef6b5cdae0242
