### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by Jursh** [godarklight/DarkMultiPlayer#340]
whenever I try connecting to a couple of modded war servers i get the following messege
"Connection error: An attempt was made to access a socket in a way forbidden by its access permissions."
did i install it wrong? am i using the wrong version? (2.2.1) the servers i am trying to connect to are 96.38.160.30:6702 and 77.100.173.102:6704

**Comment by godarklight** [comment]
I've never actually seen this error message before - It comes from C#/mono. If I had to guess, I'd say that your firewall software is playing up - but normally that shows "Connection aborted by software in your host machine".

Just to verify, does this happen with all servers or just those 2?

**Comment by oldmud0** [comment]
Sounds like firewall problems. Usually Windows Firewall comes up, blocks your connections, and asks for a ransom of admin privileges. Other AVs block applications silently.
