### ISSUE TITLE
huge save file / Kerbals file (Career_log)

### ISSUE THREAD

**Issue by BlackPilami** [godarklight/DarkMultiPlayer#342]
Hello,

We have a problem on our server we have a huge quicksave.sfs (~32Mo).
It's coming from a few Kerbals Carrer logs : 
like our Agara Kerman with 92603 lines.

Thanks in advance for your help.

**Comment by RockyTV** [comment]
Well, I'd guess that this is not a DMP bug, but a KSP bug. I'm not closing this until someone proves that this is indeed a KSP bug.

**Comment by BlackPilami** [comment]
The quicksave.sfs is created by the server with the kerbals txt files and the other config files. The problem is coming from the AgaraKerman.txt.

**Comment by RockyTV** [comment]
One question, does the career log of the specified kerbal (AgaraKerman) has repeated entries?

**Comment by BlackPilami** [comment]
Yes.
A client error ?
thousand
				0 = Recover
				0 = Land,Kerbin
				0 = ExitVessel,Kerbin
				0 = Flight,Kerbin
				0 = BoardVessel,Kerbin
				0 = Recover
				0 = Land,Kerbin
				0 = ExitVessel,Kerbin
				0 = Flight,Kerbin
				0 = BoardVessel,Kerbin
				0 = Recover
				0 = Land,Kerbin
				0 = ExitVessel,Kerbin
				0 = Flight,Kerbin
				0 = BoardVessel,Kerbin
				0 = Recover

**Comment by godarklight** [comment]
@RockyTV this was the broken method I was complaining about, the latest commit to master should fix this. After the development version gets tested properly we'll tag it and release :)

**Comment by RockyTV** [comment]
Oh. Sorry, I just realized this could be a DMP bug when I read it the second time. My bad.
