### ISSUE TITLE
Connection Error: Connected Party Did Not Properly Respond

### ISSUE THREAD

**Issue by islandboy198** [godarklight/DarkMultiPlayer#344]
I host my server from my own computer with forwarded ports. I have checked everything on my side and I cant seem to figure out what is causing this issue. When I run the server and try to connect in game I am faced with this error message after a minute of it trying to connect:

Connection error: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

I've tried running a fresh server setup, updating my client and server, checking the ports, checking my firewall, but I just cant seem to figure out what is causing this issue. I'll also point out that in the host console I am not getting any messages that indicate anyone has tried to connect or join the server. So it seems the request is getting stopped somewhere before my server catches it.

![9d39cfd6e3](https://cloud.githubusercontent.com/assets/5841057/9145580/2f967db4-3d1b-11e5-977c-c9ff01ac7e86.jpg)

**Comment by oldmud0** [comment]
There are too many parameters to check. Do other kinds of servers work?

**Comment by islandboy198** [comment]
Other servers seem to work fine. This is the same error message I get weather or not the server is even running, so something tells me it solely a server issue. My main confusion with this issue is that my server worked just fine up until recently. I've double and triple checked simple things like IP and correct ports, but cant seem to find an issue there.

In the end, with what I've found I would understand if we were unable to find a fix for this issue, mainly with it being so vague, but if anyone has any ideas I would be glad to hear them.

**Comment by RockyTV** [comment]
Upload your KSP.log to pastebin and link it here.

**Comment by islandboy198** [comment]
Sorry for the wait, had a busy weekend.

Here is my KSP.log: http://pastebin.com/aLmExkcn

**Comment by cn04** [comment]
According to your log, you tried to connect to a server with the IP address 99.187.145.8.

When it worked, were you trying to connect to it from *outside* your LAN? If it's correctly port-forwarded, and you try to connect to that 'public' IP address, it should work. But if you try that address from a computer *inside* the same LAN that the server machine is on, it won't work.

To reiterate, when connecting to the server from outside the LAN, use that external IP address. When connecting from inside (possibly from the same computer that is hosting the server), use the *internal* IP address of the server machine. This is typically in the form 192.168.x.x, or 10.0.x.x (although it might differ, depending on your router). On a Windows machine, this can be found using the 'ipconfig' command.

So, if you're inside the same LAN as the server machine, run 'ipconfig' in a Windows commandline on the server machine, and try connecting to the address listed in the 'IPv4 Address' field. If you're outside the network, and the server is properly port-forwarded, using the public address should work.

Good luck!

**Comment by JaayyJaay** [comment]
I am having the same issue.. I have a friend connected to my local server that is being hosted on a dedicated machine, but I cannot connect from inside my local network from a different machine.
I try Internal and external (public) IP, and neither of them work.
This is really annoying as I can sit here and watch my friends play on my server, but I can't connect.
