### ISSUE TITLE
Vehicle stuck on launchpad, can't remove, nobody can launch vessels

### ISSUE THREAD

**Issue by MrFronk** [godarklight/DarkMultiPlayer#345]
I was inside the VAB and wanted to launch my ship. The game crashed. I log back into the game and a vehicle (it say's mine, but it has 1200 parts in 500 stages) is stuck on the lanchpad. Fly or Recovery doesn't work.Other people also can't launch because of it, so essentially we are 'stuck'.

![image](https://cloud.githubusercontent.com/assets/8642195/9428209/ca367aa4-499b-11e5-97a4-b27fe5bfcaa2.png)

I tried to resolve by taking a plane and crash it into the launchpad, but this is undoable since I get 0.1 FPS (probably because of all the parts being loaded),

also posted here to find help:
https://www.reddit.com/r/KerbalSpaceProgram/comments/3i2my2/darkmultiplayer_stuck_on_launchpad_bug/

**Comment by dsonbill** [comment]
I noticed in the reddit thread someone mentioned nukeksc - while this will probably work, would it be possible for you to isolate the vessel in the Universe folder of the server before doing so? Just look for an excessively large file in the vessels.

Seeing the content of the entry may help us to resolve this from happening in the future.

**Comment by MrFronk** [comment]
Hi there,

Unfortunatelly, the server host used shift-del to remove the massive file (he did notice it once searching for it). One thing to note though, I thought no-one could work on the server, but it turns out other people could (all) recover the vehicle, get the money/reward, and then launch their own stuff. I myself wan't able to however. it would dissapear, but once in VAB clicking launch new ship, it would tell me again there's something stuck on the platform, which leads me to suggest that there is something wrong with my personal file on the server.

I'm sorry I can't provide more information as it no longer seems to be there. If it will happen again, I will ask for a copy of the file.
