### ISSUE TITLE
DMP Menu error

### ISSUE THREAD

**Issue by vanadiumOxide** [godarklight/DarkMultiPlayer#346]
My DMP keeps not showing the menu. 
Already reinstalled KSP, dmp mod, and other mods. Please help

![image](https://cloud.githubusercontent.com/assets/14161005/9715205/651b5312-5588-11e5-9b79-abbf214d26ae.png)

**Comment by godarklight** [comment]
Can you upload KSP_folder/KSP.log to pastebin so I can check how KSP loads it :)

**Comment by vanadiumOxide** [comment]
Sure. Here it is
http://pastebin.com/NM8su5zz

**Comment by RockyTV** [comment]
For some reason DMP cannot create or access the settings file (I think). Try running the game as administrator.
