### ISSUE TITLE
Connection ended: Unhandled error while syncing

### ISSUE THREAD

**Issue by neso7** [godarklight/DarkMultiPlayer#352]
Hello,

After port forwarding and correct set up, Im unable to connect to my own or other servers with the error above. Here is the server log file for the error report when trying to connect to my own server:

http://pastebin.com/5AseGWui

This is the Kerbal Log from the game 

http://pastebin.com/qcJcEQXy

**Comment by godarklight** [comment]
I keep seeing this bug - It's caused by a missing KSP/GameData/Squad folder

**Comment by neso7** [comment]
Thank you so much! Also, great job on the mod!
