### ISSUE TITLE
Handshake failure: invalid key for user

### ISSUE THREAD

**Issue by DeSoviet** [godarklight/DarkMultiPlayer#354]
no matter what server I try to join, it will not let me join any server, all it says is this: Handshake failure: invalid key for user, is there any fix for this?

**Comment by RockyTV** [comment]
Go to `KSP folder\GameData\DarkMultiPlayer\Plugins\Data` and delete the **privatekey.txt** and **publickey.txt** files. It should work.

**Comment by DeSoviet** [comment]
thank you, I will try that now

**Comment by DeSoviet** [comment]
the files keep reappearing in the folder when I boot the game back up, odd, any fix for this please?

**Comment by oldmud0** [comment]
Where is the :facepalm: emoticon when you need it?
Yes, a new set of keys are made when you delete them. Just connect to a server and everything should be fine.

**Comment by DeSoviet** [comment]
i keep deleting them and yet, it still says I cannot connect, this is flip the table levels of frustration currently.

**Comment by RockyTV** [comment]
You only have to delete them once. You don't need to keep deleting them after you did the first time.

**Comment by Stokkie64** [comment]
yeah seems like a different issue. Would the logs be able to help with this?

**Comment by godarklight** [comment]
@RockyTV deleting the keys will *cause* this problem, you're supposed to delete DMPServer/Universe/Players/playername.txt :)

Luckily DMP backs up their keys in KSP/saves/DarkMultiPlayer :P

Invalid key just means you've wiped your install without copying over the DMP save, or the DMP plugin - it is indeed this issue.

**Comment by darkjump** [comment]
I am in 1.2.1 with DMP 1.2.1 I followed the coneseil give give but I still can not connect (server: Nuts - Mod Friendly Server) but this does not work on any server and I do not know what to do. Surprising its progress in 1.1.3 but not in 1.2.1. WHY ?? : /

**Comment by RockyTV** [comment]
Ask the server admin to remove your key file from the server's universe.

**Comment by knir12** [comment]
> Ask the server admin to remove your key file from the server's universe.

This did it, thanks, i actually kept my science. Didnt expect that.
