### ISSUE TITLE
Vessel Loading and Flight Status (in menu) is corrupted

### ISSUE THREAD

**Issue by hmarch00** [godarklight/DarkMultiPlayer#355]
Landed crafts are shown as Splashed on (body) and in-flight vessels have no description and can not be viewed by other players.

**Comment by RockyTV** [comment]
This should have been fixed already. What DMP and KSP versions?

**Comment by Camogamer** [comment]
I have experienced similar behavior with KSP v105.1028 and DMP v0.2.2.2, but the issue did not seem consistent.
