### ISSUE TITLE
Starting problem with MODS: Assembly Unity-Engine missing

### ISSUE THREAD

**Issue by RoovyLP** [godarklight/DarkMultiPlayer#360]
When I do start the server with Plugins (irrelevant which ones) there are two errors:

1st:
`[11:00:24][FATAL] : Error in main server thread, Exception: System.IO.FileLoadException: Die Datei oder Assembly "Assembly-CSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" oder eine Abhängigkeit davon wurde nicht gefunden. Ungültiger Zeiger (Ausnahme von HRESULT: 0x80004003 (E_POINTER))
Dateiname: "Assembly-CSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" ---> System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei DarkMultiPlayerServer.DMPPluginHandler.CurrentDomain_AssemblyResolve(Object sender, ResolveEventArgs args)
   bei System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
   bei System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
   bei System.Reflection.RuntimeAssembly.GetExportedTypes()
   bei DarkMultiPlayerServer.DMPPluginHandler.LoadPlugins()
   bei DarkMultiPlayerServer.Server.Main()`

2nd:
`Unbehandelte Ausnahme: System.IO.FileLoadException: Die Datei oder Assembly "Assembly-CSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" oder eine Abhängigkeit davon wurde nicht gefunden. Ungültiger Zeiger (Ausnahme von HRESULT: 0x80004003 (E_POINTER)) ---> System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei DarkMultiPlayerServer.DMPPluginHandler.CurrentDomain_AssemblyResolve(Object sender, ResolveEventArgs args)
   bei System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
   bei System.Reflection.RuntimeAssembly.GetExportedTypes()
   bei DarkMultiPlayerServer.DMPPluginHandler.LoadPlugins()
   bei DarkMultiPlayerServer.Server.Main()`

So, what to do now? Evrything I tried out didn't worked so I think theres something with Unity or the server.
Thanks for help and this great mod!

**Comment by furyanPDX** [comment]
You need to make sure those files exists in the same folder as the server executable: "DMPServer.exe"
