### ISSUE TITLE
Can't connect to Nonameships.pw stock server; Scenario Err

### ISSUE THREAD

**Issue by LemonHeroman** [godarklight/DarkMultiPlayer#364]
Okay Im a vetran KSP player clocking in roughly 700+ hours in this game.. I only recently installed DMP on my Steam KSP folder about 2 or three weeks ago.

This bug happened on 4/14/2016, The day before this issue, the game ran fine and still connected to the Nonameships.pw Stock Server. (Listed on the dmp.org site server list)

I don't know much about the issue being cause from, but here is the overall stats for my computer.
(Stock computer) HP Pavilion Slimline. 
Windows 8.1 
Intel I3-2130 3.4ghz cpu (Integrated Graphics*)
4GB DDR3 RAM (3.88 allocate-able)
No GPU or Graphics card..
For some stupid reason DirectX isn't allowed to support updating drivers from Dx10 to Dx11..

And that's it.. 

*(blaming Best Buy for this poor choice, and since they thought a Quad-core I3 is just as good as a graphics card for "games"; Now I dislike them further..)

![20160414154849_1](https://cloud.githubusercontent.com/assets/18471409/14543346/2fb35cbe-0259-11e6-857c-4eda3cf73fc4.jpg)
Screenshot of the error message.. Yes the server worked and connected fine the day before..

**Comment by godarklight** [comment]
I'll need the log file for this - SCENARIO_DATA is where mods store their data, but it also does the stock things global to the game, like funds, reputation etc.

KSP_folder/KSP.log on windows - paste it into pastebin.

**Comment by LemonHeroman** [comment]
Never mind, I did a bit of digging around and it seems this was missing.. 

ICSharpCode.SharpZipLib.dll

I decided to backup my 'keys' and then reinstalled DMP..
That fixed the issue and nothing else has happened so far..
Guess that is a "Fix" to what this situation may be for other players that somehow experience this issue.
