### ISSUE TITLE
Asteroids failing to spawn with OPM/Kopernicus

### ISSUE THREAD

**Issue by martindevans** [godarklight/DarkMultiPlayer#369]
I'm running a DMP server with several mods installed and I'm getting no asteroids spawning in multiplayer although there are plenty of them in single player. Client side logs contain things like:

```
[LOG 03:13:01.558] RemoteTech: SatelliteManager: OnVesselCreate(e87701f8-c051-4287-9264-5a85c1e5bf51, Ast. ZJS-769)
[LOG 03:13:01.560] [Vessel Ast. ZJS-769]: Destroyed. No crews were aboard.
[LOG 03:13:01.586] [Kopernicus]: New object found near Dres: Ast. ZJS-769!
[LOG 03:13:01.611] RemoteTech: SatelliteManager: OnVesselDestroy(e87701f8-c051-4287-9264-5a85c1e5bf51, Ast. ZJS-769)
[LOG 03:13:01.612] RemoteTech: SatelliteManager: UnregisterProto(e87701f8-c051-4287-9264-5a85c1e5bf51)
[LOG 03:13:01.630] [229.1667] DarkMultiPlayer: Killing non-server asteroid e87701f8-c051-4287-9264-5a85c1e5bf51, we don't own the asteroid-spawning lock
[LOG 03:13:01.631] [229.2209] DarkMultiPlayer: Skipping the removal of vessel e87701f8-c051-4287-9264-5a85c1e5bf51, name: Ast. ZJS-769, not a server vessel.
```

So it seems like the asteroid is spawned locally (including being picked up by other mods such as Remote Tech) then being destroyed by DMP because of the asteroid spawn lock.

I do have [Outer Planets Mod](http://forum.kerbalspaceprogram.com/index.php?/topic/93999-112-outer-planets-mod-20-complete-overhaul-better-terrain-nicer-terrain-textures-improved-scatter-etc-21-may/) installed, which I guess probably changes the asteroid spawning logic.

Complete mod list:

- DarkMultiPlayer
- KWRocketryRedux-GraduatedPwr
- SpaceY-Lifters
- SpaceY-Expanded
- kOS
- TweakScale
- InfernalRobotics-LegacyParts
- FerramAerospaceResearch
- MechJeb2
- InfernalRobotics
- KAS
- ExtraPlanetaryLaunchpads
- ModuleManager
- RemoteTech
- EnvironmentalVisualEnhancements-HR
- KIS
- JettisonFuel
- KerbalEngineerRedux
- KronalVesselViewer
- PlanetShine
- PlanetShine-Config-Default
- RealPlume
- RealPlume-StockConfigs
- Scatterer-sunflare
- EngineLighting
- EnvironmentalVisualEnhancements
- ModularFlightIntegrator
- SmokeScreen
- KWRocketryRedux
- DockingPortAlignmentIndicator
- RasterPropMonitor
- RasterPropMonitor-Core
- ProceduralFairings
- Scatterer
- Kopernicus
- OuterPlanetsMod
- NearFutureElectrical
- B9PartSwitch
- CommunityResourcePack
- NearFutureElectrical-Core
- CommunityTerrainTexturePack
- KerbalJointReinforcement

**Comment by RockyTV** [comment]
I have implemened a little workaround for the asteroid spawning issue with Kopernicus that happened due to its module removing all loaded `ScenarioDiscoverableObjects`. The workaround prevents the module from loading.

Fixed in 72b88a0 (unstable), please test and let me know if asteroids are spawning as they should.
