### ISSUE TITLE
Could not turn off reverting flight option when using CUSTOM difficulty setting

### ISSUE THREAD

**Issue by K-Hideyoshi** [godarklight/DarkMultiPlayer#370]
No related option generated in the GameplaySettings.txt.
Is there any trick to disable this option by hand?
thanks

**Comment by RockyTV** [comment]
Uhm, I actually thought that I included the setting, but I didn't.

If you want to disable revert you can go to DMP options and click the
"Enable Revert" button, and revert will be disabled.

Seems like someone will have to update the gameplay settings... *looks at
me*

**Comment by K-Hideyoshi** [comment]
I have tried that button but it doesn't work, We can still  revert our ship no matter what status is the button. And I've tried [generate universe from saved game](Hard career mode), still doesn't work...

**Comment by RockyTV** [comment]
Fixed in 58ffc307c0b6abc0ad7eeaed7c119aa84b8d73d6
