### ISSUE TITLE
doesn't work on linux servers

### ISSUE THREAD

**Issue by tidle** [godarklight/DarkMultiPlayer#372]

**Comment by tidle** [comment]
please make it work on linux!!!

**Comment by RockyTV** [comment]
It works on Linux, all you have to do is use Mono.

**Comment by tidle** [comment]
what's "MONO"?

**Comment by RockyTV** [comment]
https://mono-project.com

**Comment by tidle** [comment]
it just says Connecting...

**Comment by RockyTV** [comment]
Please watch this video: https://www.youtube.com/watch?v=C46uqHlf0jU

**Comment by kekersdev** [comment]
@Xinayder Could you describe how to run the dotnet version (from darklight.my.to/dmp) of the server specifically?
It says that .NET Runtime is missing even though the latest version of `mono-complete` is installed:
```
You must install .NET to run this application.

App: /root/dmp/linux-x64/DMPServer
Architecture: x64
App host version: 6.0.29
.NET location: Not found

Learn about runtime installation:
https://aka.ms/dotnet/app-launch-failed

Download the .NET runtime:
https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=debian.12-x64&apphost_version=6.0.29
```
