### ISSUE TITLE
Error While Syncing

### ISSUE THREAD

**Issue by Rcannon95** [godarklight/DarkMultiPlayer#376]
I have been unable to connect to my server. I keep getting this error. http://pastebin.com/UsiGy7VG

I have forwarded the port.
Added Firewall exceptions for KSP, KSP64, and DMP
Verified my Cache.

I cannot think what else I can do and I am at a loss.

**Comment by RockyTV** [comment]
I'm aware of this issue that says `TimeWarp.SetRate` is an invalid method, however, I can't find why it occurs. Until then, no fix :(

**Comment by Rcannon95** [comment]
Okay.

**Comment by CHazz** [comment]
any news about this? :
Unknown sent connection end message, reason: Unhandled error while syncing!

**Comment by RockyTV** [comment]
Yes, use the development branch or 0.2.3.1 which are compatible with 1.1.3

If you're still on 1.1.2 use 0.2.3.0

**Comment by callmebackdraft** [comment]
i am sorry to inform you but i get this same issue on a fresh ksp install (version 1.1.3) with both the devbranch and 2.3.1. so it seems that its still an issue.

all Firewall settings have been checked, heck i even shut down the firewall completely. all to no avail

**Comment by RockyTV** [comment]
Could you provide your KSP.log file (upload to Pastebin)?

**Comment by callmebackdraft** [comment]
sure of course, here you go:
http://pastebin.com/N6c6xV3Q

**Comment by callmebackdraft** [comment]
When checking the log the error seems different from the one that Chazz was experiencing,
my instance seems to be throwing a divide by zero exception: 

`[LOG 15:21:56.151] [498.8542] DarkMultiPlayer: Generating 18 new kerbals
[LOG 15:21:56.152] [498.8543] DarkMultiPlayer: Threw in Update, state STARTING, exceptionSystem.DivideByZeroException: Division by zero
  at KerbalRoster.SetExperienceTrait (.ProtoCrewMember pcm, System.String traitName) [0x00000] in <filename unknown>:0
  at CrewGenerator.RandomCrewMemberPrototype (KerbalType type) [0x00000] in <filename unknown>:0
  at KerbalRoster.GetNewKerbal (KerbalType type) [0x00000] in <filename unknown>:0
  at DarkMultiPlayer.VesselWorker.LoadKerbalsIntoGame () [0x00000] in <filename unknown>:0
  at DarkMultiPlayer.Client.StartGame () [0x00000] in <filename unknown>:0
  at DarkMultiPlayer.Client.Update () [0x00000] in <filename unknown>:0
[LOG 15:21:56.157] [498.8543] DarkMultiPlayer: Sending disconnect message, reason: Unhandled error while syncing!`

**Comment by RockyTV** [comment]
@callmebackdraft try deleting your `Universe` folder on the server and restart it.

**Comment by callmebackdraft** [comment]
My universe folder is empty, however i still tried deleting it to no avail

**Comment by RockyTV** [comment]
What server version are you using?

**Comment by callmebackdraft** [comment]
Server and client version 2.3.1 atm but also tried both dev versions

**Comment by RockyTV** [comment]
Can you please create a new issue reporting the error you're getting? As you said before, it is unrelated to the error the OP had.

**Comment by callmebackdraft** [comment]
I will do that first thing in the morning (its midnight over her right now)
Thanks for investigating the issue so far.
