### ISSUE TITLE
Unhandled Error While Syncing

### ISSUE THREAD

**Issue by CaptainRedlemon** [godarklight/DarkMultiPlayer#377]
Me or my friends cant join my server, in the server tab its comes up with : 
Client -username- disconnected in Send Network Message, endpoint [::ffff-IP-];49445, error Unable to write data to the transport connection; An exsisting connection was forcibly closed by the host.

**Comment by CaptainRedlemon** [comment]
If it doesn't come up with the error above it comes up with : 
No connection could be because made the target machine actively refuses it.

**Comment by RockyTV** [comment]
Upload KSP.log to Hastebin please?

**Comment by oldmud0** [comment]
Check the router for correct port forwarding.

**Comment by CaptainRedlemon** [comment]
I'm doing LAN

**Comment by RockyTV** [comment]
Firstly, your ModuleManager seems to be throwing exceptions. And the reason
you can't connect to the server is because you're using DMP 0.2.3.1 with
KSP 1.1.2. If you don't want to update KSP to 1.1.3, use 0.2.3.0.

**Comment by CaptainRedlemon** [comment]
Thanks, Im stupid.

**Comment by oldmud0** [comment]
Wait, why doesn't DMP detect the KSP version being used to be lower than the minimum KSP version and just shut down?

**Comment by RockyTV** [comment]
Thank you for noting that @oldmud0. I think we thought it wasn't necessary to check if the mod was compatible with the revision, and we forgot about it. I tagged again and I am just waiting for @godarklight to rebuild it.
