### ISSUE TITLE
Unable to connect: "error while syncing"

### ISSUE THREAD

**Issue by callmebackdraft** [godarklight/DarkMultiPlayer#383]
Hey,

@RockyTV asked me to post this issue seperatly.

Afterdoing a clean install of both KSP (version 1.1.3) and darkmultiplayer (version 2.3.1)
I seem unable to connect to my local server (on the same machine). It throws an "error while syncing"  error, before posting issue i did all of the following:

- made firewall exceptions for both KSP and DMP (client and server)
- tried the DEV version of both the dmp client and server
- deleting the universe folder (even though it remained empty)

I uploaded KSP.log to pastebin: http://pastebin.com/N6c6xV3Q

When i checked the log i noticed the following:

my instance seems to be throwing a divide by zero exception:

```
[LOG 15:21:56.151] [498.8542] DarkMultiPlayer: Generating 18 new kerbals
[LOG 15:21:56.152] [498.8543] DarkMultiPlayer: Threw in Update, state STARTING, exceptionSystem.DivideByZeroException: Division by zero
  at KerbalRoster.SetExperienceTrait (.ProtoCrewMember pcm, System.String traitName) [0x00000] in <filename unknown>:0
  at CrewGenerator.RandomCrewMemberPrototype (KerbalType type) [0x00000] in <filename unknown>:0
  at KerbalRoster.GetNewKerbal (KerbalType type) [0x00000] in <filename unknown>:0
  at DarkMultiPlayer.VesselWorker.LoadKerbalsIntoGame () [0x00000] in <filename unknown>:0
  at DarkMultiPlayer.Client.StartGame () [0x00000] in <filename unknown>:0
  at DarkMultiPlayer.Client.Update () [0x00000] in <filename unknown>:0
[LOG 15:21:56.157] [498.8543] DarkMultiPlayer: Sending disconnect message, reason: Unhandled error while syncing!
[LOG 15:21:56.158] [498.8545] DarkMultiPlayer: Disconnected, reason: Connection ended: Unhandled error while syncing!
```

**Comment by RockyTV** [comment]
Okay, I have absolutely no clue why this is happening, but I know that we _may_ have redundant code in `VesselWorker.cs` regarding sending kerbals to the server. Unfortunately, as our master branch is currently supporting the 1.2 pre-release, you wouldn't be able to benefit from the fixes we push to the branch.

I'll see what I can do and perhaps the redundant code is the issue. But I'd advise to wait for the 1.2 release, which happens to be [tomorrow](http://forum.kerbalspaceprogram.com/index.php?/topic/149285-kerbal-space-program-12-loud-clear-release-date-and-more/).
