### ISSUE TITLE
DMP Not Loading Correctly

### ISSUE THREAD

**Issue by FiberSprite** [godarklight/DarkMultiPlayer#387]
Hello There, I Just Installed DMP and for some reason it will not load at all. I checked the logs and its having a error

`[ERR 00:44:38.734] AssemblyLoader: Exception loading 'DarkMultiPlayer': System.Reflection.ReflectionTypeLoadException: The classes in the module cannot be loaded.
  at (wrapper managed-to-native) System.Reflection.Assembly:GetTypes (bool)
  at System.Reflection.Assembly.GetTypes () [0x00000] in <filename unknown>:0 
  at AssemblyLoader.LoadAssemblies () [0x00000] in <filename unknown>:0 `

Heres the pastebin of the full KSP log. http://pastebin.com/uJe7NhhY I cut it off where the last DMP item was loaded.

**Comment by 81ninja** [comment]
If you downloaded the client at d-mp.org (even via the updater), it's the old version (compatible with KSP 1.1.3 only). There are a few dev builds around, but an official 1.2 compatible version hasn't been released yet.

**Comment by FiberSprite** [comment]
Ohh, Thank you @81ninja
