### ISSUE TITLE
Changes made through the Tracking Station aren't saved

### ISSUE THREAD

**Issue by 81ninja** [godarklight/DarkMultiPlayer#392]
DMP doesn't save to the server changes made to vessels through the tracking station.

E.g. I go to the tracking station, rename a vessel and redesignate its type (say from Debris to Probe). The changes aren't saved to the server unless I click on Fly to control them which isn't always desirable. (plus the loading)

It's not a big issue while renaming a ship or two, but when redesigning a whole satellite network it can make things really boring. (load ship - rename - load tracking station - rinse, repeat...)

**Comment by RockyTV** [comment]
I think we need to push vessel privacy ASAP in order to allow modifications to vessels, then hook OnVesselRenamed (I think there's an event with this name) and send the update to the server if the player owns it.

**Comment by 81ninja** [comment]
I just noticed that, in the case of vessels that have no crewable parts or probe cores, this also makes them impossible to rename (no button to click). 

By privacy you mean vessel ownership and permissions?

Fixing this is probably a matter of hooking to the event, and sending the vessel update to the server and clients. Would this be a waste of work or conflict with the future ownership system?

**Comment by RockyTV** [comment]
>By privacy you mean vessel ownership and permissions?

Yes. It's ideal to have the system in place, otherwise anyone can modify the vessel. I think perhaps we should just fetch the update lock if it isn't active, rename and release the lock.
