### ISSUE TITLE
DMP Not Working

### ISSUE THREAD

**Issue by Zetrious** [godarklight/DarkMultiPlayer#393]
I'm having a current issue with KSP, basically DMP just won't work at all I tried unzipping it like opeing DarkMultiPlayer then GameData and dragging DMP or what ever it's called into GameData. That doesn't work, I tried the DMPUpdater to install it for me and it still won't work. Any reasons, P.S I do have modulemanager installed. I also running KSP's latest released update.

**Comment by RockyTV** [comment]
As said before many times, the latest DMP release doesn't work with KSP 1.2.x. Rename the DMPUpdater executable to `DMPUpdater-development.exe` and run it to get a working version for 1.2.

**Comment by Zetrious** [comment]
Rocky, I apologize if you feel annoyed about the issue I brought up. I tried looking up about the issue and found nothing related so this was my only choice. If it were instructed on the website where I get it from I must of over read it. Sorry for wasting your time and repeating many times.

**Comment by Zetrious** [comment]
Rocky, as well I do not access to the 'executable' setting. I don't understand how but i'll try downloading it a couple more times if I still have issues i'll let you know.

**Comment by RockyTV** [comment]
You just have to rename the DMPUpdater executable (DMPUpdater.exe) to `DMPUpdater-development.exe`
