### ISSUE TITLE
[Linux] Badly formatted version (with file named DMPUpdated-release.exe)

### ISSUE THREAD

**Issue by Litarvan** [godarklight/DarkMultiPlayer#394]
Hello,
I think this simple screen will resume my problem :

![If you see this message you are a cool guy](https://i.gyazo.com/3277dd0e11a03b4259493865f0a435ff.png)

I am using Steam Native on Arch Linux, thanks you for any help

**Comment by RockyTV** [comment]
Why are you using Wine to run the updater? DMP runs perfectly fine on Mono, so why use Wine?

**Comment by Litarvan** [comment]
Oh ok, seems logic :/ (You should precise it, and also you could precise it on the Download page because, when i downloaded it first, i saw a .exe i thought 'ok this is not working on linux')

Working now, thank you :)

**Comment by RockyTV** [comment]
>  (You should precise it, and also you could precise it on the Download page because, when i downloaded it first, i saw a .exe i thought 'ok this is not working on linux')

It's in the readme :P

**Comment by Litarvan** [comment]
There is no README when downloading the Updater, it downloads the .exe itself :p

**Comment by RockyTV** [comment]
Oh, I thought you mentioned the mod itself. Anyways, I'll add a note to the mod's readme then.
