### ISSUE TITLE
Multiplayer window doesn't show up

### ISSUE THREAD

**Issue by Jammerbam** [godarklight/DarkMultiPlayer#397]
When i load up my game, the connection window doesn't show in the main menu.
[output_log.txt](https://github.com/godarklight/DarkMultiPlayer/files/643914/output_log.txt)

**Comment by RockyTV** [comment]
You're running an incompatible DMP version. If you're running KSP 1.2.2, use the [http://godarklight.info.tm/dmp/build/latest/DMPClient.zip](development version).
