### ISSUE TITLE
User server-side data not saving.

### ISSUE THREAD

**Issue by MetalGearDaner** [godarklight/DarkMultiPlayer#398]
Hello,

I've got a problem with my DMP server, wich is currently running latest 0.2.4.1 version, and science mode. Yesterday one of our users was unable to join the server. The console log printed this warnings:

`[02:44:31][INFO] : New client connection from ::ffff:84.12....
[02:44:31][INFO] : Client Godi failed to handshake: Invalid key for user
[02:44:31][INFO] : Disconnecting client Godi, sent HANDSHAKE_REPLY (Invalid key for user) to endpoint ::ffff:84.12....`

After searching through forums and looking for a solution, we concluded stopping the server and deleting /Universe/Players/Godi.txt file, where Godi's RSA Key Value was stored. Once server started again, the user was able to connect, but the server stopped saving the science and launched vessel data, while other stuff such as saved rocket designs, aren't lost. I believe this data is kept client-side. It'd explained the reason why it's saved, while science and vessels aren't.

This is the configuration of the server: http://pastebin.com/0udc8zd9

I don't really understand why is this happening. Maybe is because of the key issue he had, or because of a bad configuration... I would appreciate very much some help on this.

My best regards,
Daniel.

**Comment by RockyTV** [comment]
Could you upload the server log to some file hosting website like Pastebin and link it here?

**Comment by MetalGearDaner** [comment]
Of course. This are the logs when the user (Godi) was unable to connect, when we deleted RSAKey, and when user disconnected: 
http://pastebin.com/UQNGWZ9f

This are the logs of the day after, when he had the same problem (vessels and science not saving). I gave him the lost science by changing one of the files of the server where science value is saved. But server still doesn't save science and vessels:
http://pastebin.com/ejsgyLj7

Hope you can find a solution to this, and thank you very much for your help!

**Comment by RockyTV** [comment]
Two things I noticed:
- `[03:28:15][DEBUG] : Godi sent connection end message, reason: Error handling SET_SUBSPACE message`
- All of the vessels he controls are being removed by the server

I don't know why both of these happened, but I do know why none of his vessels are being saved: they are being removed from the server (perhaps he's terminating them?).

**Comment by MetalGearDaner** [comment]
Are they beeing removed after inmediately he disconnect? Or after it? And, in the DMP code, wich event makes "Error handling SET_SUBSPACE message" appear?

**Comment by 81ninja** [comment]
You can terminate (i.e. remove, delete) orbiting vessels in the Tracking Station. What RockyTV meant is that the user may be removing the vessels himself. If he isn't doing it manually himself (by terminating or recovering the ships), maybe some mod he has installed is.

"Error handling SET_SUBSPACE" is a bug that happens often if you keep warping and stopping warp or changing warping speeds up and down rapidly.

**Comment by MetalGearDaner** [comment]
I've talk to the user, and he told me that he hasn't terminated any of his vessels. He has no other mods installed than just Dark Multiplayer.

If "Error handling SET_SUBSPACE" is the bug you described, I personally don't think may be the issue. I believe it may be related to the ASR Key Value deletation, because he has this problem since then.

**Comment by 81ninja** [comment]
Question: 
1. is the server saving science and vessels for other players?
2. where is this server running, on your own desktop or a dedicated server on a version of Windows Server?
