### ISSUE TITLE
DMP Acting like it was never installed

### ISSUE THREAD

**Issue by Liquidtessla4** [godarklight/DarkMultiPlayer#406]
### Environment
- OS: Windows 10
- Mono: What is this?

### Description
I have installed DMP the night before I posted this. Everything was going fine and enjoyed it so much that I got three hours of sleep that "morning". Today, after I was done with school, I started up KSP only to find that DMP was gone. I checked the Gamedata folder, the files were there. I restarted the game in 32bit, still wouldn't work. I even manually ran KSP as admin (I have bought KSP from steam) which didn't solve the issue.

It seems that DMP has diapered of the surface of the planet even though the mod is installed. I have updated Norton in the time between, but I am not sure if that is the issue.

### Additional Info
I have copied and pasted the text from the .log to a .txt file...
[KSP-LOG-DOCUMENT.txt](https://github.com/godarklight/DarkMultiPlayer/files/823073/KSP-LOG-DOCUMENT.txt)

**Comment by RockyTV** [comment]
Why are you installing a server on your KSP client as well? It might be the
issue.

**Comment by Liquidtessla4** [comment]
The video I watched on how to install DMP told me to add in the DMPServer along with the DarkMultiPlayer folder.

Video Link: https://www.youtube.com/watch?v=lcbecpJY6GI

Image:
![gamadata-folder](https://cloud.githubusercontent.com/assets/26236950/23682574/59b6cd6a-0349-11e7-943b-927e724651e0.PNG)

**Comment by RockyTV** [comment]
It's wrong. Try removing the DMPServer folder from GameData.

**Comment by Liquidtessla4** [comment]
I removed the DMPServer folder, and DMP is still not showing up. I installed Module Manager (by sabian) to see if ti can find any issues.

**Comment by Liquidtessla4** [comment]
Just started KSP, Module Manager stated "0 modules loaded".

Do you have any ideas RockyTV? I kinda want to play with DMP again soon. :(

**Comment by RockyTV** [comment]
Can you upload your KSP.log?

**Comment by Liquidtessla4** [comment]
Which is the text document called KSP?

**Comment by Liquidtessla4** [comment]
[KSP-LOG-DOCUMENT-2.txt](https://github.com/godarklight/DarkMultiPlayer/files/826358/KSP-LOG-DOCUMENT-2.txt)

**Comment by Dan-Shields** [comment]
You still have the server installed at "GameData\DMPServer". It's causing duplicate libraries. Try deleting this folder.

**Comment by Liquidtessla4** [comment]
Deleted folder, and it still will not workie!

**Comment by Dan-Shields** [comment]
Well the log that you posted shows clearly that the folder still exists:

`[LOG 16:37:12.958] AssemblyLoader: Loading assembly at C:\Program Files (x86)\Steam\steamapps\common\Kerbal Space Program\GameData\DMPServer\DarkMultiPlayer-Common.dll`

**Comment by Liquidtessla4** [comment]
For some reason my friend's install disapered at the same time mine did. I don't understand how they are connected, but they are. What is with my luck lately?!
