### ISSUE TITLE
RCS & SAS are disabled

### ISSUE THREAD

**Issue by steevegldev** [godarklight/DarkMultiPlayer#407]
### Environment
- OS: Windows Server 2012 R2
- Mono: 

### Description
RCS & SAS are disabled

### Additional Info
Brand new server setup, all by default. Just connected and tried to launch. Then, noticed the RCS & SAS are disabled. I can't figured out why.

Do not happen in solo mode.

**Comment by RockyTV** [comment]
Can you give more details? We can't help you if you just say "rcs is disabled".

**Comment by steevegldev** [comment]
I didn't juste said that, read again. Already give all details I can. 

Copied files in folder. Launched the DMPServer.exe. Connected to the server. Launched a vessel. No RCS & SAS.

**Comment by RockyTV** [comment]
Could you provide your KSP.log please? Upload it to pastebin.

**Comment by steevegldev** [comment]
There it is: http://pastebin.com/DdcyfCc3

**Comment by RockyTV** [comment]
You don't even have DMP installed... And it's likely to be an issue with KSP (you might be using a kerbal without a certain trait which doesn't allow you to turn on SAS and RCS).

**Comment by steevegldev** [comment]
I used this instruction http://d-mp.org/w/Howto/Server/installation.

DMPServer.exe is present in my kerbal's root folder. I don't understand what you mean by saying "not installed"

**Comment by RockyTV** [comment]
Clearly you don't know how to read instructions. The page says: 
> Option a) Extract the DarkMultiPlayer zip to a folder, **Not under the KSP or GameData folders.** 

Anyways, DMP is not installed. I read the log you provided and there's no mention of DMP in it.

**Comment by Dan-Shields** [comment]
> Extract the DarkMultiPlayer zip to a folder, Not under the KSP or GameData folders.

DMPServer.exe should be nowhere near your ksp folder, and from the looks of it you haven't installed the client like RockyTV said. The full instructions are here https://github.com/godarklight/DarkMultiPlayer#install

**Comment by steevegldev** [comment]
Since I put DMPUpdater.exe next to KSP.exe and DMPServer.exe. After ran DMPUpdater.exe that didn't fix my issue immediately. But when I tested later, that worked.

So, I not sure what was the problem and how that has been fix. But it's working now...

Thanks for your time.,

**Comment by oldmud0** [comment]
Issue summary: Strange issue happened. DMP did not turn out to be installed, even though he "connected" to the server. After a while, DMP magically works again.
