### ISSUE TITLE
GUI has no Keybind

### ISSUE THREAD

**Issue by Fabricio20** [godarklight/DarkMultiPlayer#409]
### Environment
- OS: Windows 10
- Mono: -

### Description
GUI has no Keybind to reopen.

### Additional Info
I've noticed that if we close the DMP GUI inside the server and then leave/get disconnected we will have to restart KSP to get the GUI to show up again, since there is no keybind. (This is quite frustrating when you have about 50 mods).

Guess it wouldn't be that hard to just have a keybind to reopen the GUI?

**Comment by RockyTV** [comment]
What do you mean with "close the DMP GUI inside the server"? Do you mean the connection window?

**Comment by Fabricio20** [comment]
Yes, the actual GUI, close the chat, and click the DMP button to hide it, then get disconnected and you will have to restart the game for that same GUI to show up again.

**Comment by RockyTV** [comment]
You can toggle it back by joining a server and clicking the toolbar button, iirc.

**Comment by Fabricio20** [comment]
How am I supposed to join a server _without_ the GUI?

**Comment by RockyTV** [comment]
Right, I wasn't understanding the issue. I'll push a fix in a bit.
