### ISSUE TITLE
KSP DMP Client Window has disappeared.

### ISSUE THREAD

**Issue by TwinKerbal** [godarklight/DarkMultiPlayer#412]
- Windows 10
- Mono: your Mono version here

### Description
KSP DMP client window is completely gone.  I installed it correctly into Gamedata, tried reinstalling, running DMP Updater, and running as admin.  

### Additional Info
I run KSP on Steam.  I also have a lot of part mods.
[KSP.txt](https://github.com/godarklight/DarkMultiPlayer/files/1009307/KSP.txt)

**Comment by 81ninja** [comment]
```Access to the path "C:/Program Files (x86)/Steam/steamapps/common/Kerbal Space Program/KSP_x64_Data/../saves\DarkMultiPlayer\Ships\VAB" is denied.```
1) Delete GameData\ModuleManager.2.7.5.dll. (you have 2 ModuleManager version installed)
2) Delete the folder saves\DarkMultiPlayer and try again. Run as a normal user and launch KSP x64 from Steam as usual.

There are other errors in your log file as well, related to InfernalRobotics, and you may have some permissions problems in your KSP folder as a whole. Do you know how to reset them?

**Comment by TwinKerbal** [comment]
I'll be honest, I don't know how to fix half of my problems. For one, when I try to delete the save, it keeps telling me accessed denied, even though I'm the only user on the computer. I also don't know how to reset, but hey I can do step one. So can you help me?

**Comment by 81ninja** [comment]
I guess this is detailed enough: http://winaero.com/blog/how-to-take-ownership-and-get-full-access-to-files-and-folders-in-windows-10/
You should probably take ownership and give yourself access to your whole KSP folder that way. You'll be able to delete the DMP save folder afterwards (if that alone doesn't solve the problem).

One note though, make copies of servers.xml, privatekey.txt and publickey.txt before deleting the save folder. You'll need these files to connect to servers you were previously playing in.

**Comment by TwinKerbal** [comment]
Alright.
After I did this all, I ran KSP once more.  It showed the disclaimer window, then after I hit "Accept", nothing.  Apparently the DarkMultiPlayer save keeps on cropping up, shooting everything to hell..  It's hell to delete once, so is there any workaround for that?

**Comment by 81ninja** [comment]
Can you post a fresh log file?

In another glance at the previous one, you probably have your KSP installation corrupted, looks like you are in mod hell. For example, you have multiple dlls for the same mods installed.
```Mod DLLs found:
...
BahaTurret v1.0.0.0 / v0.11.1.6
BahaTurret v1.0.0.0 / v0.11.1.6
BahaTurret v1.0.0.0 / v0.11.1.6
BahaTurret v1.0.0.0 / v0.11.1.6
BahaTurret v1.0.0.0 / v0.11.1.6
...```
This is for BDArmory, apparently there's a folder called BDArmory-master full of duplicates.

Besides the mod files themselves, your installation may have been corrupted to the point that it can't be fixed, so you'd probably be better off with a fresh install, and reinstalling the mods using CKAN.

**Comment by TwinKerbal** [comment]
Oh boy, I guess I'm in for a wild ride.  Gotta delete each individual subfolder before deleting the entire folder in order to avoid the "admin is needed" bug.

I'll update you once I reinstall.

**Comment by TwinKerbal** [comment]
Update: Thank you SO much!  A random Windows process was using KSP for some reason, all I had to do was end it.  Again, thanks so much, after redownloading KSP it works!

**Comment by ezeakeal** [comment]
Sorry to comment on a closed issue - but this bug re-appeared for me.
A full reinstall was a way of fixing it, but that was a pain.

I found that opening `Kerbal Space Program\GameData\DarkMultiPlayer\Plugins\Data\settings.cfg`
and changing disclaimer to 0 will trigger the disclaimer to reappear, but also bring back the server browser.

Worked for my mate as well, hope it helps

**Comment by superraptor2** [comment]
Thank you so much ezeakeal! I was searching for the same kind of thing because my KSP is 1.4.3 but DMP only 1.4.2 and only if the disclaimer pops up then the client window pops up (so only one time ever) But setting the disclaimer back to 0 help me out alot, Thanks!

**Comment by Destructogaming** [comment]
I'm getting the same issue, but there are a few differences.

- I don't have module manager, and DMP is the only mod installed.

- all solutions currently listed do not work
