### ISSUE TITLE
GUI Not Appearing

### ISSUE THREAD

**Issue by TheWaffleDimension** [godarklight/DarkMultiPlayer#420]
### Environment
- OS: 64-Bit Windows 10
- Mono: 

### Description
The GUI is not showing whatsoever. The log shows it being loaded, and the save for it is created, but the save shows as incompatible. No disclaimers show; no GUI whatsoever appears. I'm on KSP version ID 1622. Everything is installed correctly, both manually and with the updater (I tried both ways).

### Additional Info
https://hastebin.com/agitumetul.vbs

EDIT: Added a little more information.

**Comment by RockyTV** [comment]
You're probably using the latest release (0.2.4.3) with 1.2.2, when it supports 1.3. Try updating your KSP or using 0.2.4.2 with 1.2.2.

**Comment by TheWaffleDimension** [comment]
That was the problem, thanks! It was a bit confusing on which version of DMP to choose, because it doesn't state what version of KSP the DMP version is compatible with.
