### ISSUE TITLE
KSP 1.3.1 Support

### ISSUE THREAD

**Issue by d4rkd0s** [godarklight/DarkMultiPlayer#430]
![image](https://user-images.githubusercontent.com/2348814/31261152-55d1bc68-aa07-11e7-9092-8ed603d11739.png)

### Environment
Windows 10 x64

### Description
Plugin no longer launches with new KSP Version.

### Additional Info
Nothing else really needed, mod just needs some testing and a version bump.

**Comment by d4rkd0s** [comment]
Confirmed, updated Client and Server and the popup still shows. Looks like its 1.3.0 mod and KSP is now 1.3.1

**Comment by d4rkd0s** [comment]
Think we need to bump this to `1`?
https://github.com/godarklight/DarkMultiPlayer/blob/99bca17078a351683aded1f431d44875d32951bf/Client/Utilities/CompatibilityChecker.cs#L53

**Comment by RockyTV** [comment]
In short, yes. Long version: we need to check if there were any breaking changes in 1.3.1, check the API changes, modify our current code if necessary and then release a new version.

_I'm surprised as to why people quickly want to file an issue when there's a self-explanatory text that tells you why it's not working_

**Comment by d4rkd0s** [comment]
I understand why its not working. I am willing to assist 👍  test, and modify and code I can understand.

**Comment by d4rkd0s** [comment]
@RockyTV Apologies for the confusion, wasn't complaining or filing a "bug" issue, just want to get teh work done to get DMP back up n' running for KSP 1.3.1. 

First of, it appears raw changes to the "game" are  ([source](https://wiki.kerbalspaceprogram.com/wiki/Version_history)):
- Localization fixes and enhancements
- Bugfixes and performance improvements
- Other undefined enhancements

As for the API changes, I am not familiar enough with [KSP API](https://kerbalspaceprogram.com/api/annotated.html) to determine/find a changelog.

Next I am going to fork and make changes to this line and test.
https://github.com/godarklight/DarkMultiPlayer/blob/99bca17078a351683aded1f431d44875d32951bf/Client/Utilities/CompatibilityChecker.cs#L53

**Comment by RockyTV** [comment]
No need to, check the unstable branch. I pushed some pending PRs and if you want to test the changes, feel free to do so. Any feedback is appreciated.

**Comment by d4rkd0s** [comment]
Thanks very much @RockyTV
