### ISSUE TITLE
Not being prompted for the disclaimer 

### ISSUE THREAD

**Issue by Seaniboy2009** [godarklight/DarkMultiPlayer#431]
### Environment
- OS: 

### Description
Hello,

I was on the mod and was working fine(on my own server) i closed the game to go out, on coming back i launched the game again and was not being prompted for the disclaimer, and the mod was not loaded.
I did not change anything, the computer was not even restarted, i closed the game and opened it again about an hour later.

My friend also has the same issue, it worked fine the first time he launched it, but now he is not prompted with the disclaimer.

### Additional Info
Use this space to post links to client logs (`KSP.log`) and server logs (`dmpserver.log`), screenshots or anything else you may find useful to help us address the issue. Please upload log files to a file hosting service like [Hastebin](https://hastebin.com).

**Comment by Eld0r** [comment]
Please tell us your game and DMP versions.

That's okay, disclaimer is showed only once.
Your answer is stored in servers.xml in the Plugin Data directory of your installation:
...\Steam\SteamApps\common\Kerbal Space Program\GameData\DarkMultiPlayer\Plugins\Data

But the mod should be loaded, when no error msg appear.
Are you up to date and use the DMUpdater.exe out of the directory of KSP.exe?

**Comment by RockyTV** [comment]
Correction: your config is located in `[KSP root]/GameData/DarkMultiPlayer/Plugins/Data/settings.cfg`.

We can't help you if you don't provide the `KSP.log` file.

**Comment by Seaniboy2009** [comment]
Ahh i thought it was every time, thank you for clearing that up. so no error message popped up, but one the main Kerbal menu there is no DMP box to allow me to connect to a server its just the normal Kerbal menu

KSP Version 1.3.1
DMP Version latest version i use the DMUpdater and i only installed it lastnight.

Sorry i am at work just now so i am unable to provide the KSP.log file, i will provide when i get home if still needed.

**Comment by RockyTV** [comment]
Did a message dialog popup saying DMP was incompatible, right when you ran DMP?

**Comment by Seaniboy2009** [comment]
No message at all popped up.

**Comment by Seaniboy2009** [comment]
Ok i have launched it again, and i am now getting the incompatibility working like i did before when it was working. but the join server tab is not there.

**Comment by Eld0r** [comment]
true. no bug, a feature.
if you got the incompatibility message the mod aborts loading. this is the defined intention of the compatibility checker.
You must use the unstable build or wait for an update...

**Comment by Eld0r** [comment]
true. no bug, a feature.
if you got the incompatibility message the mod aborts loading. this is the defined intention of the compatibility checker. 

My pull request for adding a "try to load anyway, but be aware there may be compatibility issues" button for the developer build was rejected. 
Reason: there is already a splitting in four versions:
release, development, unstable, wip

You must use the unstable build or wait for an update...

**Comment by RockyTV** [comment]
Apparently GitHub can't detect more than an issue at the "close issue keywords". Fixed in the PR referenced above.
