### ISSUE TITLE
Source files missing ?

### ISSUE THREAD

**Issue by basox70** [godarklight/DarkMultiPlayer#455]
### Environment
- OS: W10

### Description
can't compile using visual studio 2017

### Additional Info
some type or namespace seems absent ?
![image](https://user-images.githubusercontent.com/6689304/50497458-0b90dc00-0a38-11e9-97f6-f8dcf68ee69e.png)

**Comment by zeroalpha** [comment]
it compiles fine for me with Windows 10 and VS 2017.

Can you give a bit more detail on the steps you took ?

**Comment by basox70** [comment]
i made a fork on my github, then i cloned, and opened the .sln with VS2017, it's an enterprise edition

**Comment by zeroalpha** [comment]
Can you show me the full error messages ?

And have you copied the KSP Files to your directory ?

## Compiling
- Copy the following assemblies from `[KSP root folder]/KSP_Data/Managed`:
  * `Assembly-CSharp`
  * `Assembly-CSharp-firstpass`
  * `UnityEngine`
  * `UnityEngine.UI`
- Paste the copied assemblies where `DarkMultiPlayer.sln` is located at.

**Comment by basox70** [comment]
I've copied the files, i have still the problem (685 errors, most of them are "type or namespace missing", a few are "'ConfigNode' is unreachable due to its protection level" ) 
![image](https://user-images.githubusercontent.com/6689304/50520850-e301f400-0ac2-11e9-9e6d-78fc15fb7c41.png)
![image](https://user-images.githubusercontent.com/6689304/50520929-56a40100-0ac3-11e9-9f5b-a27008e03888.png)

**Comment by GermanDevCoding** [comment]
@basox70 I've tried it too and got 0 errors

> 1>------ Neues Erstellen gestartet: Projekt: DarkMultiPlayerCommon, Konfiguration: Debug Any CPU ------
> 1>  DarkMultiPlayerCommon -> D:\My\Desktop\Coding\DarkMultiPlayer\Common\bin\Debug\DarkMultiPlayer-Common.dll
> 2>------ Neues Erstellen gestartet: Projekt: Client, Konfiguration: Debug Any CPU ------
> 3>------ Neues Erstellen gestartet: Projekt: Server, Konfiguration: Debug Any CPU ------
> 2>  Client -> D:\My\Desktop\Coding\DarkMultiPlayer\Client\bin\Debug\DarkMultiPlayer.dll
> 3>  Server -> D:\My\Desktop\Coding\DarkMultiPlayer\Server\bin\Debug\DMPServer.exe
> ========== Alles neu erstellen: 3 erfolgreich, 0 fehlerhaft, 0 übersprungen ==========

**Comment by basox70** [comment]
well, i'll go back to beginning, and try again

**Comment by basox70** [comment]
well, i don't know why, but it works ¯\_(ツ)_/¯
Maybe the files didn't copy well, i don't know
thanks for the help to both of you
