### ISSUE TITLE
There is no damages when I using the BDArmory mod

### ISSUE THREAD

**Issue by SaigyoujiYuyuko233** [godarklight/DarkMultiPlayer#467]
### Environment
- OS: Windows 10
- Mono: -

### Description
When I play with my friend with the BDArmory(mod), I tried to shoot to my friend's vehicle and I saw that there are damages to my friend's vehicle but my friend tell me that in his side there is no damages.

### Additional Info
![image](https://user-images.githubusercontent.com/39913604/72664886-f4a39a00-3a3d-11ea-87e8-8ccaabea83c6.png)
![image](https://user-images.githubusercontent.com/39913604/72664890-fb321180-3a3d-11ea-86d4-088816a10d64.png)

Then, several seconds later, my friend's vehicle return to its original shape.
My friend and me installed the same mod.
[Settings.txt](https://github.com/godarklight/DarkMultiPlayer/files/4080757/Settings.txt)
[mod-control.txt](https://github.com/godarklight/DarkMultiPlayer/files/4080758/mod-control.txt)
![image](https://user-images.githubusercontent.com/39913604/72664971-c2466c80-3a3e-11ea-9d18-f19b672478f3.png)

**Comment by obwan02** [comment]
For this to properly work you need support for the mod on the server which isn't possible unless there is a plugin for DMP for BDArmoury
