### ISSUE TITLE
Auto stop warp based on other players actions (MCW_VOTE)

### ISSUE THREAD

**Issue by Deadpan110** [godarklight/DarkMultiPlayer#71]
As seen in plugins such as Kerbal Alarm Clock and MechJeb - warping for single player is stopped on certain conditions.
Kerbal Alarm Clock alows a user to set an alarm and stores the time this will occur (along with event type and notes) and such a mechanism could be used in DMP MCW_VOTE.

Very related to issue/enhancement #67 and possibly beyond the scope of what DMP is designed for but I felt I should include it here for reference/ideas and completeness.

## Scenario

A player is en-route to Duna in "DoinDuna Craft MK1" and has a SOI in 6 days, they decide that during this period they will make a start on designing their next craft.

Another player is on their way to Minmus on a science gathering mission and wants to warp the entire way there.

### Possible solution

The server could be notified; then check for the approaching SOI and stop warp with a notice "Warp Stopped - 'DoinDuna Craft MK1' has reached SOI.

Again, this is very related to issue/enhancement #67 but would come from the DMP Client / Server (although the idea could be achieved via a plugin or mod).

This could also work for active maneuver nodes so as to let a player switch what they are doing (like - go build something in VAB) letting other players warp but only to where they want to be.

**Comment by godarklight** [comment]
This is handled via MCW_LOWEST :)
