### ISSUE TITLE
Server Browser not displaying

### ISSUE THREAD

**Issue by JohannesMP** [godarklight/DarkMultiPlayer#77]
On rare occasions when I boot up my two clients (Which live on two completely separate folders with their own set of files), the server browser will not be visible on either of them, but looking at Player.log *(download <a href=https://copy.com/VH62RBEi2BuUqoD0>here</a>)* and the in-Game Debug view, you can clearly see that DMP's files were loaded correctly, and it mentiones the hashed files at the bottom.

![screenshot_2014-06-06_16 49 28](https://cloud.githubusercontent.com/assets/662874/3200901/003aa6ce-ed82-11e3-8318-e33b5537753e.png)
<sub>Note: this was actually me trying to prepare for another testing session. Notice how neither client has the server browser visible</sub>

It seems like one of two things might be triggering this: I just ran the updater (`DMPUpdater-development.exe`) and I started both of the clients in quick succession of one another, so they were both loading at the same time, albeit from two completely separate directories.

It's not a terribly pressing issue, since it does tend to resolve itself after quitting and restarting both clients:
![screenshot_2014-06-06_17 01 18](https://cloud.githubusercontent.com/assets/662874/3201011/1dd5b22c-ed83-11e3-8ca2-cf403f36b610.png)

But it's still a little unnerving since this shouldn't be happening. Just something to look out for I guess.

**Comment by godarklight** [comment]
Closing this old bug unless we can get more info.
