### ISSUE TITLE
Kerbal EVA/clone issues

### ISSUE THREAD

**Issue by JoshBlake** [godarklight/DarkMultiPlayer#89]
Below was tested with d24be7b;

When in orbit and you take a Kerbal on EVA, if you leave the Kerbal on a ladder, any timewarping (if it lets you) or quicksave reloading will cause the Kerbal to drop off the ladder and end up roughly 100m away floating around.

I'm also still seeing Kerbal cloning issues (related to #19):
* After docking two 3-man capsules, I could EVA 6 kerbals, and return all 6 back to their capsules. 
* After a quicksave reload with all 6 kerbals EVA on ladders (which then made them spawn in a 200 diameter EVA constellation), there was still space for them to return to the capsules, but the roster pictures showed another 6 kerbals already present, making a total of 12 kerbals.
* The quicksave reload also spawned a seventh EVA kerbal, which was unable to get a seat aboard the vessel after six others already reboarded.

In the end, I had a dual-capsule (docked) vessel with 12 kerbals (six clones) and one more EVA clone with no seat.

**Comment by godarklight** [comment]
Closing this old bug as it has been a really long time, I suspect this may have been fixed with the kerbal rework.
