### ISSUE TITLE
Spectator docking glitchy

### ISSUE THREAD

**Issue by JoshBlake** [godarklight/DarkMultiPlayer#99]
When spectating someone who is docking to another craft, the vessels become super glitchy, repeating the same moment with abnormally high rotations in proximity to each other away from the docking position, about 2-3x per second. This continues until the next 30s AVR update.

**Comment by godarklight** [comment]
All docking is glitchy, there's nothing special about spectator dockings, so I'll close this one and handle it in the others :)
